export const addManagerInitValues = {
  idPhoto: "",
  town: "",
  email: "",
  firstName: "",
  gender: "",
  isActive: "active",
  lastName: "",
  middleName: "",
  mobile: "",
  nationality: "",
  nationalId: "",
  passportNum: "",
  profileImage: "",
  branches: [],
  allyId: "",
  status: "add",
  password: "",
  dob: "",
  isAllyManager: false,
};
