/* eslint-disable prettier/prettier */
export const addCustomerInitValues = {
  businessCard: "",
  cityId: undefined,
  clientMutationId: "",
  companyName: "",
  dob: "",
  driverLicense: "",
  driverLicenseExpireAt: "",
  email: "",
  firstName: "",
  gender: "male",
  isActive: "active",
  lastName: "",
  licenseFrontImage: "",
  licenseSelfieImage: "",
  middleName: "",
  mobile: "",
  nationalIdExpireAt: "",
  nationalIdVersion: "",
  nationalityId: "",
  nid: "",
  passportExpireAt: "",
  passportFrontImage: "",
  passportNumber: "",
  status: "citizen",
  profileImage: undefined,
  nidImage:undefined,
  borderNumber:"",
  visaImage:undefined,
  fakeEmail: "",
  customerClass: "basic_member",
  blockingStatus: "",
  blockingAllies: [],
  blockingReason: ""
};
