query Branches($allyCompanyIds: [ID!], $pickupHandoverBranchId: ID) {
  branches(allyCompanyIds: $allyCompanyIds, pickupHandoverBranchId: $pickupHandoverBranchId) {
    collection {
      id
      area {
        arName
        enName
      }
      districtNameAr
      districtNameEn
    }
  }
}
