query BusinessRequestDetails($id: ID!) {
  businessRequestDetails(id: $id) {
    acceptedOffer {
      additionalKilometer
      allyClass
      allyCompanyArName
      allyCompanyEnName
      allyCompanyId
      allyCompanyName
      statusLocalized
      allyRate
      businessRentalId
      carInsuranceFull
      carInsuranceStandard
      createdAt
      id
      kilometerPerMonth
      offerPrice
      policyAndConditions
      status
    }
    additionalNotes
    allyCompanyId
    arBusinessActivity
    arMakeName
    arModelName
    arPickUpCityName
    bookingNo
    businessActivityId
    businessActivityName
    businessRentalOffers {
      additionalKilometer
      allyCompanyId
      businessRentalId
      carInsuranceFull
      carInsuranceStandard
      createdAt
      id
      kilometerPerMonth
      offerPrice
      status
      allyCompanyName
      statusLocalized
    }
    carImage
    carModelId
    carVersionId
    commercialRegistrationCertificate
    commercialRegistrationNo
    companyEmail
    companyName
    companyPhone
    createdAt
    customerName
    enBusinessActivity
    enMakeName
    enModelName
    enPickUpCityName
    id
    insuranceId
    insuranceName
    makeId
    makeName
    modelName
    numberOfCars
    numberOfMonths
    otherCarName
    phone
    pickUpCityId
    pickUpCityName
    pickUpDatetime
    status
    userId
    year
  }
}
