query CarVersion($id: ID!) {
  carVersion(id: $id) {
    arName
    carModel {
      enName
      arName
      id
      make {
        arName
        enName
        id
      }
    }
    vehicleType {
      id
      arName
      enName
    }
    features {
      id
      nameAr
      nameEn
    }
    enName
    id
    image
    images
    name
    year
    isActive
  }
}
