query AllyManager($id: [ID!]) {
  allyManager(id: $id) {
    allyProfile {
      allyId
      branches
      email
      firstName
      gender
      idPhoto
      lastName
      middleName
      nationalId
      nationality
      passportNum
      town
      dob
    }
    createdAt
    id
    isActive
    mobile
    profileImage
  }
}
