query Features($isParent: Boolean, $isActive: Boolean, $category: String) {
  features(isParent: $isParent, isActive: $isActive, category: $category) {
    collection {
      nameAr
      nameEn
      id
      icon
    }
  }
}
